let productId:number=10;
console.log(productId);
let productName:string="Phone";
console.log(productName);
let productAvailable:boolean=true;
console.log(productAvailable);
let productSize:any="10.5";
console.log(productSize);
    productSize=10.5;
    console.log(productSize);
let productCompany:void=undefined;
console.log(productCompany);