var productId = 10;
console.log(productId);
var productName = "Phone";
console.log(productName);
var productAvailable = true;
console.log(productAvailable);
var productSize = "10.5";
console.log(productSize);
productSize = 10.5;
console.log(productSize);
var productCompany = undefined;
console.log(productCompany);
